### ISSUE TITLE
req.body is always blank in the userController

### ISSUE THREAD

**Issue by corey-mitchell** [project3org/Group-To-Do-Lists#1]
For whatever reason, no matter what I send to my API, the req.body is always blank so I can't move forward. I know that the API call is at least hitting my controller because I receive back my own messages telling me that the firstName field cannot be blank.
![issue1 1](https://user-images.githubusercontent.com/37916145/47708356-e16b9b00-dbfb-11e8-9c1a-f9962949196f.PNG)

If I choose to console log out req.body in the userController folder, I receive back an empty object. Like so:
![issue1 2](https://user-images.githubusercontent.com/37916145/47708481-2db6db00-dbfc-11e8-998b-d32fb2c8d7a0.PNG)
![issue1 3](https://user-images.githubusercontent.com/37916145/47708491-327b8f00-dbfc-11e8-86bd-cd053ddfd55d.PNG)

**Comment by corey-mitchell** [comment]
I am using a body parser and I have "Content-Type": "application/json" in my header... I'm soo lost.

**Comment by antoniojgage** [comment]
http://toolsqa.com/postman/post-request-in-postman/

**Comment by corey-mitchell** [comment]
Thank you @antoniojgage for helping me solve this one.

The issue was none other than the elusive user error. Code was totally fine, but my postman skills could clearly use some work.
