### ISSUE TITLE
[DOM] Found 2 elements with non-unique id

### ISSUE THREAD

**Issue by corey-mitchell** [project3org/Group-To-Do-Lists#11]
Console error:
![issue5 1](https://user-images.githubusercontent.com/37916145/48062017-5ef85380-e186-11e8-9533-35a4134a4305.PNG)

I am getting this error saying that their are two fields with the same id... But there isn't!!!

Here is my component code.

```

    // Renders Component
    render() {
        return (
            <div>
                {/* Creates Sign In Dialog */}
                <Dialog
                open={this.props.openSignInDialog}
                onClose={this.props.closeDialogs}
                aria-labelledby="form-dialog-title"
                >
                    <form id='signInForm' onSubmit={this.handleUserSignIn}>
                    <DialogTitle id="form-dialog-title">Sign In</DialogTitle>
                    <DialogContent>
                        <DialogContentText>
                        Please enter your user email and password.<br />
                        If you do not have an account please sign up.<br /><br />
                        </DialogContentText>
                        <TextField
                        autoFocus
                        margin="dense"
                        id="signInEmail"
                        label="Email Address"
                        type="email"
                        fullWidth
                        />
                        <TextField
                        margin="dense"
                        id="signInPassword"
                        label="Password"
                        type="password"
                        fullWidth
                        />
                        <DialogContentText style={errorStyle}>
                        {this.props.errorMessage}
                        </DialogContentText>
                    </DialogContent>
                        <DialogActions>
                            <Button onClick={this.props.closeDialogs} color="primary">
                            Cancel
                            </Button>
                            <Button type="Submit" color="primary">
                            Sign In
                            </Button>
                        </DialogActions>
                    </form>
                </Dialog>
            </div>
        );
    };
};

```

As you can see, there are only two fields both with different ID's. I don't understand what's going on... Google just tells me to make sure it's wrapped in a form tag. Which it is!

Edit: Some people say that they can submit the form even with these issues, but I cannot because it either can't target the value or the value always comes back blank.

**Comment by corey-mitchell** [comment]
https://www.chromium.org/developers/design-documents/create-amazing-password-forms

here is a link to the 'More info' article that the console has provided me.

**Comment by antoniojgage** [comment]
Do 2 of them exist on the page at all? Does the page come up if you comment out the entire form and try and render it?

**Comment by antoniojgage** [comment]
Which file is this located? Send me the branch & file name.

**Comment by corey-mitchell** [comment]
Unfortunately, I'm not too sure what was causing this. But rather than rely on the Material-UI component to do the work, I set up the form like it was react day one. (Setting a 'value' state with and onChange function.) Now I just pass the value to my api, so there is no need to target the TextFields. Therefore, I can just delete the ID and move on with my day with everything working.
